# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SerialPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(533, 615)
        self.widget = QtWidgets.QWidget(window)
        self.widget.setGeometry(QtCore.QRect(0, 10, 350, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(350, 800))
        self.widget.setMaximumSize(QtCore.QSize(350, 800))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comBox_serialPortName = QtWidgets.QComboBox(self.groupBox_3)
        self.comBox_serialPortName.setMinimumSize(QtCore.QSize(80, 30))
        self.comBox_serialPortName.setStyleSheet("")
        self.comBox_serialPortName.setObjectName("comBox_serialPortName")
        self.gridLayout_4.addWidget(self.comBox_serialPortName, 0, 4, 1, 1)
        self.bradBox = QtWidgets.QComboBox(self.groupBox_3)
        self.bradBox.setMinimumSize(QtCore.QSize(80, 30))
        self.bradBox.setObjectName("bradBox")
        self.bradBox.addItem("")
        self.bradBox.addItem("")
        self.bradBox.addItem("")
        self.bradBox.addItem("")
        self.bradBox.addItem("")
        self.bradBox.addItem("")
        self.bradBox.addItem("")
        self.gridLayout_4.addWidget(self.bradBox, 1, 4, 1, 1)
        self.openSerialButton = QtWidgets.QPushButton(self.groupBox_3)
        self.openSerialButton.setMinimumSize(QtCore.QSize(80, 30))
        self.openSerialButton.setStyleSheet("")
        self.openSerialButton.setObjectName("openSerialButton")
        self.gridLayout_4.addWidget(self.openSerialButton, 6, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.dataBitsBox = QtWidgets.QComboBox(self.groupBox_3)
        self.dataBitsBox.setMinimumSize(QtCore.QSize(80, 30))
        self.dataBitsBox.setObjectName("dataBitsBox")
        self.dataBitsBox.addItem("")
        self.dataBitsBox.addItem("")
        self.dataBitsBox.addItem("")
        self.dataBitsBox.addItem("")
        self.gridLayout_4.addWidget(self.dataBitsBox, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 1)
        self.stopBitsBox = QtWidgets.QComboBox(self.groupBox_3)
        self.stopBitsBox.setMinimumSize(QtCore.QSize(80, 30))
        self.stopBitsBox.setStyleSheet("")
        self.stopBitsBox.setObjectName("stopBitsBox")
        self.stopBitsBox.addItem("")
        self.stopBitsBox.addItem("")
        self.stopBitsBox.addItem("")
        self.gridLayout_4.addWidget(self.stopBitsBox, 4, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.parityBox = QtWidgets.QComboBox(self.groupBox_3)
        self.parityBox.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        self.parityBox.setFont(font)
        self.parityBox.setObjectName("parityBox")
        self.parityBox.addItem("")
        self.parityBox.addItem("")
        self.parityBox.addItem("")
        self.parityBox.addItem("")
        self.gridLayout_4.addWidget(self.parityBox, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
        self.openSerialButton_searchport = QtWidgets.QPushButton(self.groupBox_3)
        self.openSerialButton_searchport.setMinimumSize(QtCore.QSize(80, 30))
        self.openSerialButton_searchport.setStyleSheet("")
        self.openSerialButton_searchport.setText("")
        self.openSerialButton_searchport.setObjectName("openSerialButton_searchport")
        self.gridLayout_4.addWidget(self.openSerialButton_searchport, 5, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.serialDataRead = QtWidgets.QTextBrowser(self.groupBox_2)
        self.serialDataRead.setMinimumSize(QtCore.QSize(0, 25))
        self.serialDataRead.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.serialDataRead.setStyleSheet("")
        self.serialDataRead.setObjectName("serialDataRead")
        self.gridLayout_5.addWidget(self.serialDataRead, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.groupBox_3.setTitle(_translate("window", "串口设置"))
        self.bradBox.setItemText(0, _translate("window", "9600"))
        self.bradBox.setItemText(1, _translate("window", "14400"))
        self.bradBox.setItemText(2, _translate("window", "19200"))
        self.bradBox.setItemText(3, _translate("window", "38400"))
        self.bradBox.setItemText(4, _translate("window", "57600"))
        self.bradBox.setItemText(5, _translate("window", "115200"))
        self.bradBox.setItemText(6, _translate("window", "128000"))
        self.openSerialButton.setText(_translate("window", "打开串口"))
        self.label_5.setText(_translate("window", "停止位："))
        self.label_2.setText(_translate("window", "波特率："))
        self.label.setText(_translate("window", "串口号："))
        self.dataBitsBox.setItemText(0, _translate("window", "8"))
        self.dataBitsBox.setItemText(1, _translate("window", "7"))
        self.dataBitsBox.setItemText(2, _translate("window", "6"))
        self.dataBitsBox.setItemText(3, _translate("window", "5"))
        self.label_6.setText(_translate("window", "串口操作："))
        self.stopBitsBox.setItemText(0, _translate("window", "1"))
        self.stopBitsBox.setItemText(1, _translate("window", "1.5"))
        self.stopBitsBox.setItemText(2, _translate("window", "2"))
        self.label_3.setText(_translate("window", "数据位："))
        self.label_4.setText(_translate("window", "校验位："))
        self.parityBox.setItemText(0, _translate("window", "None"))
        self.parityBox.setItemText(1, _translate("window", "Even"))
        self.parityBox.setItemText(2, _translate("window", "Mark"))
        self.parityBox.setItemText(3, _translate("window", "Odd"))
        self.label_7.setText(_translate("window", "扫描串口："))
        self.groupBox_2.setTitle(_translate("window", "接收"))
        self.groupBox.setTitle(_translate("window", "发送"))
        self.pushButton.setText(_translate("window", "发送"))


